apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: "2024-01-23T15:09:31Z"
    creationTimestamp: "2024-01-23T15:09:31Z"
    generation: 1
    name: is-test
    namespace: prod
    resourceVersion: "304668"
    uid: 6d16c1b9-23ff-4b2a-babb-1029df3a73cb
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: bitnami/nginx
      generation: 1
      importPolicy:
        importMode: Legacy
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: image-registry.openshift-image-registry.svc:5000/prod/is-test
    publicDockerImageRepository: default-route-openshift-image-registry.apps-crc.testing/prod/is-test
    tags:
    - items:
      - created: "2024-01-23T15:09:31Z"
        dockerImageReference: bitnami/nginx@sha256:b06dff7e64b254406d89f2ea34572018614b1c3714e44faad23161320e452e2b
        generation: 1
        image: sha256:b06dff7e64b254406d89f2ea34572018614b1c3714e44faad23161320e452e2b
      tag: latest
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"is-test:latest","namespace":"prod"},"fieldPath":"spec.template.spec.containers[?(@.name==\"is-test\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2024-01-23T15:09:31Z"
    generation: 2
    labels:
      app: test
      app.kubernetes.io/component: test
      app.kubernetes.io/instance: test
      app.kubernetes.io/name: is-test
      stage: prod
    name: test
    namespace: prod
    resourceVersion: "304715"
    uid: b47b3c5d-36fa-4590-822c-de49a3f1f86e
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        deployment: test
        stage: prod
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: test
          stage: prod
      spec:
        containers:
        - image: bitnami/nginx@sha256:b06dff7e64b254406d89f2ea34572018614b1c3714e44faad23161320e452e2b
          imagePullPolicy: IfNotPresent
          name: is-test
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2024-01-23T15:09:33Z"
      lastUpdateTime: "2024-01-23T15:09:33Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-01-23T15:09:31Z"
      lastUpdateTime: "2024-01-23T15:09:33Z"
      message: ReplicaSet "test-64995d46f7" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    creationTimestamp: "2024-01-23T15:09:31Z"
    labels:
      app: test
      app.kubernetes.io/component: test
      app.kubernetes.io/instance: test
      app.kubernetes.io/name: is-test
      stage: prod
    name: test
    namespace: prod
    resourceVersion: "304695"
    uid: 286c5508-09cb-465a-8c9d-4185c1755afc
  spec:
    host: prod.apps-crc.testing
    port:
      targetPort: 8080-tcp
    tls:
      insecureEdgeTerminationPolicy: None
      termination: edge
    to:
      kind: Service
      name: test
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: "2024-01-23T15:09:31Z"
        status: "True"
        type: Admitted
      host: prod.apps-crc.testing
      routerCanonicalHostname: router-default.apps-crc.testing
      routerName: default
      wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2024-01-23T15:09:31Z"
    labels:
      app: test
      app.kubernetes.io/component: test
      app.kubernetes.io/instance: test
      app.kubernetes.io/name: is-test
      stage: prod
    name: test
    namespace: prod
    resourceVersion: "304673"
    uid: 2ad03bfb-333b-4f16-9d4f-7970c5b9b2a2
  spec:
    clusterIP: 10.217.4.37
    clusterIPs:
    - 10.217.4.37
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deployment: test
      stage: prod
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
